version: '3.7'

services:
  vpn-server: 
    image: hwdsl2/ipsec-vpn-server
    environment:
       - VPN_IPSEC_PSK=xxx
       - VPN_USER=vpnuser
       - VPN_PASSWORD=xxx
    network_mode: "host"
    privileged: true
    restart: always


  vpn-client:
