version: '3.7'
services:

  osticket_app:
    image: tiredofit/osticket
    container_name: osticket_app
    volumes:
      - /mnt/osTicket/app:/www/osticket
      - /mnt/osTicket/app/logs:/www/logs
    environment:
      - CRON_PERIOD=${CRON_PERIOD}

      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

#      - ${SMTP_HOST}
#      - ${SMTP_PORT}
#      - ${SMTP_FROM}
#      - ${SMTP_TLS}
#      - ${SMTP_USER}
#      - ${SMTP_PASS}

      - INSTALL_SECRET=${INSTALL_SECRET}
      - INSTALL_EMAIL=${INSTALL_EMAIL}
      - INSTALL_NAME=${INSTALL_NAME}

      - ADMIN_FIRSTNAME=${ADMIN_FIRSTNAME}
      - ADMIN_LASTNAME=${ADMIN_LASTNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}

      - CONTAINER_NAME=${CONTAINER_NAME_1}
    networks:
      - services
    ports:
      - "8081:80"
    links:
      - osticket_db
    restart: always

  osticket_db:
    image: mariadb
    container_name: osticket_db
    volumes:
      - /mnt/osTicket/db:/var/lib/mysql
    environment:
#      - ROOT_PASS=${ROOT_PASS}
#      - DB_NAME=${DB_NAME}
#      - DB_USER=${DB_USER}
#      - DB_PASS=${DB_PASS}

       - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
       - MYSQL_USER=${DB_USER}
       - MYSQL_PASSWORD=${DB_PASS}
       - MYSQL_DATABASE=${DB_NAME}

       - ${CONTAINER_NAME_2}
    networks:
     - services
    restart: always

#  osticket-db-backup:
#    container_name: osticket-db-backup
#    image: tiredofit/mariadb-backup
#    links:
#      - osticket-db
#    volumes:
#      - ./dbbackup:/backup
#    environment:
#      - DB_HOST=osticket-db
#      - DB_TYPE=mariadb
#      - DB_NAME=osticket
#      - DB_USER=osticket
#      - DB_PASSWORD=password12345
#      - DB_DUMP_FREQ=1440
#      - DB_DUMP_BEGIN=0000
#      - DB_CLEANUP_TIME=8640
#      - COMPRESSION=BZ
#    restart: always

networks:
  services:
    driver: bridge
