version: '3.7'
services:
  ## https://hub.docker.com/r/tiredofit/mariadb
  osticket_db:
    image: tiredofit/mariadb
    container_name: osticket_db
    volumes:
      - /mnt/osTicket/db:/var/lib/mysql
    environment:
       - ROOT_PASS=${ROOT_PASS}
       - DB_USER=${DB_USER}
       - DB_PASS=${DB_PASS}
       - DB_NAME=${DB_NAME}

       - CONTAINER_NAME=osticket_db
    networks:
     - services
    ports:
     - "3306:3306"
    restart: always

  ## https://hub.docker.com/r/tiredofit/db-backup
  osticket-db-backup:
    container_name: osticket_db_backup
    image: tiredofit/db-backup
    links:
      - osticket_db
    volumes:
      - /mnt/osTicket/db-backup:/backup
      - /mnt/osTicket/custom_db_scripts:/assets/custom-scripts
    environment:
      - DB_HOST=${DB_HOST}
      - DB_TYPE=mariadb
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - POST_SCRIPT=/assets/custom-scripts/logging_utility.sh
    restart: always

  ## https://hub.docker.com/r/tiredofit/osticket
  osticket_app:
    image: tiredofit/osticket
    container_name: osticket_app
    volumes:
      - /mnt/osTicket/app:/www/osticket
      - /mnt/osTicket/app/logs:/www/logs
    environment:
      - CRON_PERIOD=10

      - DB_HOST=osticket_db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}

      - INSTALL_SECRET=${INSTALL_SECRET}
      - INSTALL_EMAIL=${INSTALL_EMAIL}
      - INSTALL_NAME=${INSTALL_NAME}

      - ADMIN_FIRSTNAME=${ADMIN_FIRSTNAME}
      - ADMIN_LASTNAME=${ADMIN_LASTNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}

      - CONTAINER_NAME=osticket_app
    networks:
      - services
    ports:
      - "8081:80"
    links:
      - osticket_db:mysql
    restart: always

networks:
  services:
    driver: bridge
